version: '3.1'

services:
  db:
    image: mariadb:latest
    ports:
      - 3306:3306 
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - database-volume:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_PORT=3306
  app:
    #image: apimovies
    build:
      context: .
    ports:
      - 5206:80
    links:
       - "db"
    volumes:
       - .\bin\Release\net7.0:/app
    command: ["dotnet", "API-Movies.dll"]

volumes:
  database-volume: